version: '3.8'

services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express-app
    networks:
      - app-network

  # Express.js application service
  express-app:
    image: rainmvc/express-app:latest
    container_name: express-app
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge